<?php

namespace Acme\AppBundle\Manager;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoManager
{
	/**
	 * Holds the Doctrine entity manager for database interaction
	 * @var EntityManager 
	 */
	protected $em;

	 /**
	 * The Fully-Qualified Class Name for our entity
	 * @var string
	 */
	protected $class;

	public function __construct(EntityManager $em, $class)
	{
		$this->em = $em;
		$this->class = $class;
		$this->repo = $em->getRepository($class);
	}

	public function newPhoto(){
		$class = $this->class;
		$photo = new $class();

		return $photo;
	}

	public function save($photo){
		$this->em->persist($photo);
		$this->em->flush();
	}

	public function update($photo){
		$this->em->merge($photo);
		$this->em->flush();
	}

	/**
	* @return Photo
	*/
	public function find($id){
		return $this->repo->find($id);
	}

	/**
	* @return array of Photo
	*/
	public function findAll($index = 0){
		$query = $this
						->repo
						->createQueryBuilder('P')
						->setFirstResult($index)
						->setMaxResults(15)
						->getQuery();

		return $query->getResult();
	}
}
