parameters:
#    acme_api.example.class: Acme\ApiBundle\Example

services:
#    acme_api.example:
#        class: %acme_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
