parameters:
   # acme_app.example.class: Acme\AppBundle\Example
   acme_app.photorepository.class: Acme\AppBundle\Manager\PhotoManager

services:
#    acme_app.example:
#        class: %acme_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_app.photo_manager:
        class: %acme_app.photorepository.class%
        arguments: 
            em: "@doctrine.orm.entity_manager"
            class: Acme\AppBundle\Entity\Photo